// This file was autogenerated by cloop - Cross Language Object Oriented Programming

package com.github.asfernandes.cloop.tests.test1;


public interface ICalc extends com.sun.jna.Library
{
	public static interface IDisposableIntf
	{
		public void dispose();
	}

	public static interface IStatusIntf extends IDisposableIntf
	{
		public static int ERROR_1 = 1;
		public static int ERROR_2 = 0x2;
		public static int ERROR_12 = IStatusIntf.ERROR_1 | IStatusIntf.ERROR_2;

		public int getCode();
		public void setCode(int code);
	}

	public static interface IStatusFactoryIntf extends IDisposableIntf
	{
		public IStatus createStatus();
	}

	public static interface IFactoryIntf extends IDisposableIntf
	{
		public IStatus createStatus();
		public ICalculator createCalculator(IStatus status) throws CalcException;
		public ICalculator2 createCalculator2(IStatus status) throws CalcException;
		public ICalculator createBrokenCalculator(IStatus status) throws CalcException;
		public void setStatusFactory(IStatusFactory statusFactory);
	}

	public static interface ICalculatorIntf extends IDisposableIntf
	{
		public int sum(IStatus status, int n1, int n2) throws CalcException;
		public int getMemory();
		public void setMemory(int n);
		public void sumAndStore(IStatus status, int n1, int n2) throws CalcException;
	}

	public static interface ICalculator2Intf extends ICalculatorIntf
	{
		public int multiply(IStatus status, int n1, int n2) throws CalcException;
		public void copyMemory(ICalculator calculator);
		public void copyMemory2(int[] address);
	}

	public static class IDisposable extends com.sun.jna.Structure implements IDisposableIntf
	{
		public static class ByReference extends IDisposable implements com.sun.jna.Structure.ByReference
		{
		}

		public static class ByValue extends IDisposable implements com.sun.jna.Structure.ByValue
		{
		}

		public void dispose()
		{
			try
			{
				vTable.dispose.invoke(this);
			}
			finally
			{
			}
		}

		public static class VTable extends com.sun.jna.Structure
		{
			public int version;

			public static interface dispose extends com.sun.jna.Callback
			{
				void invoke(ICalc.Disposable self);
			}

			public dispose dispose;
		}
	}

	public static class IStatus extends IDisposable implements IStatusIntf
	{
		public static class ByReference extends IStatus implements com.sun.jna.Structure.ByReference
		{
		}

		public static class ByValue extends IStatus implements com.sun.jna.Structure.ByValue
		{
		}

		public void dispose()
		{
			try
			{
				vTable.dispose.invoke(this);
			}
			finally
			{
			}
		}
		public int getCode()
		{
			int result;
			try
			{
				result = 				vTable.getCode.invoke(this);
			}
			finally
			{
			}
			return result;
		}
		public void setCode(int code)
		{
			try
			{
				vTable.setCode.invoke(this, code);
			}
			finally
			{
			}
		}

		public static class VTable extends com.sun.jna.Structure
		{
			public int version;

			public static interface getCode extends com.sun.jna.Callback
			{
				int invoke(Status self);
			}

			public getCode getCode;
			public static interface setCode extends com.sun.jna.Callback
			{
				void invoke(ICalc.Status self, int code);
			}

			public setCode setCode;
		}
	}

	public static class IStatusFactory extends IDisposable implements IStatusFactoryIntf
	{
		public static class ByReference extends IStatusFactory implements com.sun.jna.Structure.ByReference
		{
		}

		public static class ByValue extends IStatusFactory implements com.sun.jna.Structure.ByValue
		{
		}

		public void dispose()
		{
			try
			{
				vTable.dispose.invoke(this);
			}
			finally
			{
			}
		}
		public IStatus createStatus()
		{
			IStatus result;
			try
			{
				result = 				vTable.createStatus.invoke(this);
			}
			finally
			{
			}
			return result;
		}

		public static class VTable extends com.sun.jna.Structure
		{
			public int version;

			public static interface createStatus extends com.sun.jna.Callback
			{
				IStatus invoke(ICalc.StatusFactory self);
			}

			public createStatus createStatus;
		}
	}

	public static class IFactory extends IDisposable implements IFactoryIntf
	{
		public static class ByReference extends IFactory implements com.sun.jna.Structure.ByReference
		{
		}

		public static class ByValue extends IFactory implements com.sun.jna.Structure.ByValue
		{
		}

		public void dispose()
		{
			try
			{
				vTable.dispose.invoke(this);
			}
			finally
			{
			}
		}
		public IStatus createStatus()
		{
			IStatus result;
			try
			{
				result = 				vTable.createStatus.invoke(this);
			}
			finally
			{
			}
			return result;
		}
		public ICalculator createCalculator(IStatus status) throws CalcException
		{
			ICalculator result;
			try
			{
				result = 				vTable.createCalculator.invoke(this, status);
				StatusType::checkException(status);
			}
			finally
			{
				StatusType::clearException(status);
			}
			return result;
		}
		public ICalculator2 createCalculator2(IStatus status) throws CalcException
		{
			ICalculator2 result;
			try
			{
				result = 				vTable.createCalculator2.invoke(this, status);
				StatusType::checkException(status);
			}
			finally
			{
				StatusType::clearException(status);
			}
			return result;
		}
		public ICalculator createBrokenCalculator(IStatus status) throws CalcException
		{
			ICalculator result;
			try
			{
				result = 				vTable.createBrokenCalculator.invoke(this, status);
				StatusType::checkException(status);
			}
			finally
			{
				StatusType::clearException(status);
			}
			return result;
		}
		public void setStatusFactory(IStatusFactory statusFactory)
		{
			try
			{
				vTable.setStatusFactory.invoke(this, statusFactory);
			}
			finally
			{
			}
		}

		public static class VTable extends com.sun.jna.Structure
		{
			public int version;

			public static interface createStatus extends com.sun.jna.Callback
			{
				IStatus invoke(ICalc.Factory self);
			}

			public createStatus createStatus;
			public static interface createCalculator extends com.sun.jna.Callback
			{
				ICalculator invoke(ICalc.Factory self, IStatus status);
			}

			public createCalculator createCalculator;
			public static interface createCalculator2 extends com.sun.jna.Callback
			{
				ICalculator2 invoke(ICalc.Factory self, IStatus status);
			}

			public createCalculator2 createCalculator2;
			public static interface createBrokenCalculator extends com.sun.jna.Callback
			{
				ICalculator invoke(ICalc.Factory self, IStatus status);
			}

			public createBrokenCalculator createBrokenCalculator;
			public static interface setStatusFactory extends com.sun.jna.Callback
			{
				void invoke(ICalc.Factory self, IStatusFactory statusFactory);
			}

			public setStatusFactory setStatusFactory;
		}
	}

	public static class ICalculator extends IDisposable implements ICalculatorIntf
	{
		public static class ByReference extends ICalculator implements com.sun.jna.Structure.ByReference
		{
		}

		public static class ByValue extends ICalculator implements com.sun.jna.Structure.ByValue
		{
		}

		public void dispose()
		{
			try
			{
				vTable.dispose.invoke(this);
			}
			finally
			{
			}
		}
		public int sum(IStatus status, int n1, int n2) throws CalcException
		{
			int result;
			try
			{
				result = 				vTable.sum.invoke(this, status, n1, n2);
				StatusType::checkException(status);
			}
			finally
			{
				StatusType::clearException(status);
			}
			return result;
		}
		public int getMemory()
		{
			int result;
			try
			{
				result = 				vTable.getMemory.invoke(this);
			}
			finally
			{
			}
			return result;
		}
		public void setMemory(int n)
		{
			try
			{
				vTable.setMemory.invoke(this, n);
			}
			finally
			{
			}
		}
		public void sumAndStore(IStatus status, int n1, int n2) throws CalcException
		{
			try
			{
				vTable.sumAndStore.invoke(this, status, n1, n2);
				StatusType::checkException(status);
			}
			finally
			{
				StatusType::clearException(status);
			}
		}

		public static class VTable extends com.sun.jna.Structure
		{
			public int version;

			public static interface sum extends com.sun.jna.Callback
			{
				int invoke(Calculator self, IStatus status, int n1, int n2);
			}

			public sum sum;
			public static interface getMemory extends com.sun.jna.Callback
			{
				int invoke(Calculator self);
			}

			public getMemory getMemory;
			public static interface setMemory extends com.sun.jna.Callback
			{
				void invoke(ICalc.Calculator self, int n);
			}

			public setMemory setMemory;
			public static interface sumAndStore extends com.sun.jna.Callback
			{
				void invoke(ICalc.Calculator self, IStatus status, int n1, int n2);
			}

			public sumAndStore sumAndStore;
		}
	}

	public static class ICalculator2 extends ICalculator implements ICalculator2Intf
	{
		public static class ByReference extends ICalculator2 implements com.sun.jna.Structure.ByReference
		{
		}

		public static class ByValue extends ICalculator2 implements com.sun.jna.Structure.ByValue
		{
		}

		public void dispose()
		{
			try
			{
				vTable.dispose.invoke(this);
			}
			finally
			{
			}
		}
		public int sum(IStatus status, int n1, int n2) throws CalcException
		{
			int result;
			try
			{
				result = 				vTable.sum.invoke(this, status, n1, n2);
				StatusType::checkException(status);
			}
			finally
			{
				StatusType::clearException(status);
			}
			return result;
		}
		public int getMemory()
		{
			int result;
			try
			{
				result = 				vTable.getMemory.invoke(this);
			}
			finally
			{
			}
			return result;
		}
		public void setMemory(int n)
		{
			try
			{
				vTable.setMemory.invoke(this, n);
			}
			finally
			{
			}
		}
		public void sumAndStore(IStatus status, int n1, int n2) throws CalcException
		{
			try
			{
				vTable.sumAndStore.invoke(this, status, n1, n2);
				StatusType::checkException(status);
			}
			finally
			{
				StatusType::clearException(status);
			}
		}
		public int multiply(IStatus status, int n1, int n2) throws CalcException
		{
			int result;
			try
			{
				result = 				vTable.multiply.invoke(this, status, n1, n2);
				StatusType::checkException(status);
			}
			finally
			{
				StatusType::clearException(status);
			}
			return result;
		}
		public void copyMemory(ICalculator calculator)
		{
			try
			{
				vTable.copyMemory.invoke(this, calculator);
			}
			finally
			{
			}
		}
		public void copyMemory2(int[] address)
		{
			try
			{
				vTable.copyMemory2.invoke(this, address);
			}
			finally
			{
			}
		}

		public static class VTable extends com.sun.jna.Structure
		{
			public int version;

			public static interface multiply extends com.sun.jna.Callback
			{
				int invoke(Calculator2 self, IStatus status, int n1, int n2);
			}

			public multiply multiply;
			public static interface copyMemory extends com.sun.jna.Callback
			{
				void invoke(ICalc.Calculator2 self, ICalculator calculator);
			}

			public copyMemory copyMemory;
			public static interface copyMemory2 extends com.sun.jna.Callback
			{
				void invoke(ICalc.Calculator2 self, int[] address);
			}

			public copyMemory2 copyMemory2;
		}
	}
}
