/* This file was autogenerated by cloop - Cross Language Object Oriented Programming */

#include "CalcCApi.h"


CLOOP_EXTERN_C void Disposable_dispose(struct Disposable* self)
{
	self->vtable->dispose(self);
}

CLOOP_EXTERN_C void Status_dispose(struct Status* self)
{
	self->vtable->dispose(self);
}

CLOOP_EXTERN_C int Status_getCode(const struct Status* self)
{
	return self->vtable->getCode(self);
}

CLOOP_EXTERN_C void Status_setCode(struct Status* self, int code)
{
	self->vtable->setCode(self, code);
}

CLOOP_EXTERN_C void Calculator_dispose(struct Calculator* self)
{
	self->vtable->dispose(self);
}

CLOOP_EXTERN_C int Calculator_sum(const struct Calculator* self, struct Status* status, int n1, int n2)
{
	return self->vtable->sum(self, status, n1, n2);
}

CLOOP_EXTERN_C int Calculator_getMemory(const struct Calculator* self)
{
	return self->vtable->getMemory(self);
}

CLOOP_EXTERN_C void Calculator_setMemory(struct Calculator* self, int n)
{
	self->vtable->setMemory(self, n);
}

CLOOP_EXTERN_C void Calculator_sumAndStore(struct Calculator* self, struct Status* status, int n1, int n2)
{
	self->vtable->sumAndStore(self, status, n1, n2);
}

CLOOP_EXTERN_C void Calculator2_dispose(struct Calculator2* self)
{
	self->vtable->dispose(self);
}

CLOOP_EXTERN_C int Calculator2_sum(const struct Calculator2* self, struct Status* status, int n1, int n2)
{
	return self->vtable->sum(self, status, n1, n2);
}

CLOOP_EXTERN_C int Calculator2_getMemory(const struct Calculator2* self)
{
	return self->vtable->getMemory(self);
}

CLOOP_EXTERN_C void Calculator2_setMemory(struct Calculator2* self, int n)
{
	self->vtable->setMemory(self, n);
}

CLOOP_EXTERN_C void Calculator2_sumAndStore(struct Calculator2* self, struct Status* status, int n1, int n2)
{
	self->vtable->sumAndStore(self, status, n1, n2);
}

CLOOP_EXTERN_C int Calculator2_multiply(const struct Calculator2* self, struct Status* status, int n1, int n2)
{
	return self->vtable->multiply(self, status, n1, n2);
}

CLOOP_EXTERN_C void Calculator2_copyMemory(struct Calculator2* self, struct Calculator* calculator)
{
	self->vtable->copyMemory(self, calculator);
}

CLOOP_EXTERN_C void Factory_dispose(struct Factory* self)
{
	self->vtable->dispose(self);
}

CLOOP_EXTERN_C struct Status* Factory_createStatus(struct Factory* self)
{
	return self->vtable->createStatus(self);
}

CLOOP_EXTERN_C struct Calculator* Factory_createCalculator(struct Factory* self, struct Status* status)
{
	return self->vtable->createCalculator(self, status);
}

CLOOP_EXTERN_C struct Calculator2* Factory_createCalculator2(struct Factory* self, struct Status* status)
{
	return self->vtable->createCalculator2(self, status);
}

CLOOP_EXTERN_C struct Calculator* Factory_createBrokenCalculator(struct Factory* self, struct Status* status)
{
	return self->vtable->createBrokenCalculator(self, status);
}

